# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.systemd.services.rollback = {
    description = "Rollback BTRFS root subvolume to a pristine state";
    wantedBy = [ "initrd.target" ];
    after = [ "systemd-cryptsetup@enc.service" ]; # Wait for the luks open
    before = [ "sysroot.mount" ]; # Runs before mount the /
    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      mkdir -p /mnt

      mount -o subvolid=5 /dev/mapper/enc /mnt

      delete_subvolume_recursively() {
        IFS=$'\n'
        for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
          delete_subvolume_recursively "/mnt/$i"
        done
        btrfs subvolume delete "$1"
      }

      if [ -d /mnt/root ]; then
      	delete_subvolume_recursively /mnt/root
      fi

      if [ -e /mnt/root-blank ]; then
        btrfs subvolume snapshot /mnt/root-blank /mnt/root
      else
        echo "CAUTION: root-blank not found."
      fi

      umount /mnt
    '';
  };

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "btusb"
    "hidp"
    "hid_generic"
    "uhci_hcd"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.secrets = {
    "/var/lib/bluetooth" = "/var/lib/bluetooth";
  };
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
    ];
  };

  boot.initrd = {
    luks.devices = {
      enc = {
        device = "/dev/disk/by-uuid/8e7e951a-5b4c-4bfe-92f2-57d1f88da1d7";
        keyFileOffset = 2048;
        keyFileSize = 4096;
        keyFileTimeout = 10;
        keyFile = "/dev/disk/by-id/usb-Generic_Flash_Disk_5FDD1A0C-0:0";
      };
    };
  };

  fileSystems."/home" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "compress=zstd"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/lib/nodatacow" = {
    device = "/dev/mapper/enc";
    fsType = "btrfs";
    options = [
      "subvol=nodatacow"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/87f16c7f-16be-46da-ab99-db8f719b49a0";
      randomEncryption.enable = true;
    }
  ];

  # binds
  fileSystems."/var/lib/docker" = {
    device = "/var/lib/nodatacow/docker";
    fsType = "none";
    options = [ "bind" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
